feat: add 4626 core code
ApeAcademy/ERC20 pull request #16
Opened 2022-09-14 21:33 UTC by Ninjagod1251

I add the ERC4626 methods.

We can pre and post generate ERC4626.json with these links for pre and post hooks:
https://cookiecutter.readthedocs.io/en/stable/advanced/hooks.html#example-conditional-files-directories
https://cookiecutter.readthedocs.io/en/stable/advanced/hooks.html

2022-09-14 21:33 UTC, Ninjagod1251 commented
Please let me know if it is too simple.

Next will be the test

2022-09-14 21:42 UTC, Ninjagod1251 commented
Mint is different in ERC20 Default vs ERC4626. Let me know how I should implement the change. 

The way implemented it would be the easiest way.

2022-09-14 23:20 UTC, fubuloubu commented on {{cookiecutter.project_name}}/contracts/Token.vy
> +{%- if cookiecutter.ERC4626 == 'y' %}
I think these options might need to be mutually exclusive

2022-09-14 23:21 UTC, fubuloubu commented
Tests need updating to include `"ERC4626"` template field: https://github.com/ApeAcademy/ERC20/blob/main/tests/Basic.json

2022-09-27 21:52 UTC, fubuloubu approved these changes, later dismissed

2022-09-27 21:52 UTC, fubuloubu commented on {{cookiecutter.project_name}}/contracts/Token.vy
> +# @version 0.3.4
0.3.7 came out yesterday

2022-10-21 20:59 UTC, fubuloubu commented on .github/workflows/test.yaml
> +      with:
```suggestion
      env:
            ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
            WEB3_ALCHEMY_PROJECT_ID: ${{ secrets.WEB3_ALCHEMY_PROJECT_ID }}
```

2022-10-24 20:05 UTC, fubuloubu commented on .github/workflows/test.yaml
> +      if: matrix . template == "ERC4626"
```suggestion
      if: matrix.template == "ERC4626"
```

2022-10-24 20:06 UTC, fubuloubu requested changes
You included the temp folder by mistake?

2022-10-25 18:28 UTC, fubuloubu commented on .github/workflows/test.yaml
> +      if: matrix.template == "ERC4626"
```suggestion
      if: ${{ matrix.template == 'ERC4626' }}
```

2022-10-27 14:57 UTC, fubuloubu approved these changes

2022-10-28 17:09 UTC, merged